gossip_jeudi/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/connected_user', to: 'connectes#connected'
  resources :sessions, only: [:new, :create, :destroy]
end

gossip_jeudi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

gossip_jeudi/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

gossip_jeudi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

gossip_jeudi/app/controllers/connectes_controller.rb
class ConnectesController < ApplicationController

  before_action :authenticate_user, only: [:connected]

  def connected
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

gossip_jeudi/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

gossip_jeudi/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user_input_email = params[:email]
    user_input_password = params[:password]

    user = User.find_by(email: user_input_email)

    if user && user.authenticate(user_input_password)
      session[:user_id] = user.id
      redirect_to connected_user_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

end

gossip_jeudi/app/helpers/application_helper.rb
module ApplicationHelper
end

gossip_jeudi/app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

gossip_jeudi/app/views/connectes/connected.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome</h1>
    <h2>Bienvenue <%= current_user.email %> !</h2>
    <%= link_to "Se déconnecter", session_path(session[:user_id]), method: :delete %>
  </body>
</html>

gossip_jeudi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipJeudi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

gossip_jeudi/app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>HOME</h1>
    <p>
      <a href="<%=new_session_path%>">login</a>
    </p>
  </body>
</html>